### ISSUE TITLE
Production stuff

### ISSUE THREAD

**Issue by EricForgy** [LukeMwila/react-express-postgres#1]
Hi @LukeMwila 👋 

This repo is really helpful. Thank you 🙌 

I notice that in `client` and `server`, you have both `Dockerfile` and `Dockerfile.dev` files.

The `docker-compose.yml` file refers to `Dockerfile.dev`? 

Would the `docker-compose.yml` file be changed in any other way than `Dockerfile.dev` -> `Dockerfile` if we wanted to use the `Dockerfile` instead?

**Comment by LukeMwila** [comment]
Hi @EricForgy , 
I'm glad to hear that this repo has been helpful for you :smiley: . My apologies for the late response. You can easily swap out the `Dockerfile.dev` for the `Dockerfile` in `docker-compose.yml`. This was just simply done to create a Dockerfile dedicated to dev, whereas the other is more of a production grade Dockerfile. It's not a hard and fast rule, some people don't even bother with a `Dockerfile.dev`.

Does that answer your question?

**Comment by EricForgy** [comment]
Yes. Thanks again. I got my little 2-container app working with docker-compose, but now I am pulling my hair out trying to get it to work in Kubernetes 👴😅
